version: '2'

services:
  postgres:
    image: postgres:9.4
    # Taking password, databasename, etc from the env variables file
    env_file: ./backend/config/env
    # Volume to preserve database data
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    env_file: ./backend/config/env
    # Create a volume so I could edit the code without rebuilding container
    volumes:
      - ./backend:/home/fictionhub/backend
    # Switch to this directory
    working_dir: /home/fictionhub/backend
    # Run this command on start up, to launch a supervisor
    command: supervisord -n
    dns: 8.8.8.8    
    # Connect it to the postgres container
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - '8400:8000'
